# Editor settings
tabWidth = 4
useSpaces = true
showLineNumbers = true
highlightCurrentLine = true

# Key bindings
[[keyBindings]]
key = "ctrl+s"
action = "save"

[[keyBindings]]
key = "ctrl+q"
action = "quit" 